version: '3.8'

services:
  web:
    build: .
    command: daphne -p 8000 chatapp.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=chatapp.settings
    depends_on:
      - db

  admin:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=chatapp.settings
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: quick_connect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: