version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatapp_web:latest
    command: daphne -p 8000 chatapp.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=chatapp.settings
      - REDIS_HOST=redis
    depends_on:
      - db
    networks:
      - chatapp_network

  admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: chatapp_admin:latest
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - DJANGO_SETTINGS_MODULE=chatapp.settings
      - REDIS_HOST=redis
    depends_on:
      - db
    networks:
      - chatapp_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: quick_connect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatapp_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - chatapp_network

volumes:
  postgres_data:

networks:
  chatapp_network: